# Generated by Django 2.1.2 on 2019-07-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticcontent', '0002_static_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static',
            name='content',
        ),
    ]
