# Generated by Django 2.1.2 on 2019-07-08 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticcontent', '0003_remove_static_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
