# -*- coding: utf-8 -*-
"""
© 2018 ALL RIGHTS RESERVED BY Software Assurance LLC

Django settings for ReportIt project.

Generated by 'django-admin startproject' using Django 1.11.8.

"""
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save

User = get_user_model()

"""
Model class: Static class
Dependency: No

"""
class Static(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True,blank=True)
    content = RichTextField()
    language = models.CharField(max_length = 5,default = 'en')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, blank=True, null=True,on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("static-page", kwargs={"slug": self.slug})

def pre_save_static_receiver(sender, instance, *args, **kwargs):
    print(instance.slug)
    instance.slug = slugify(instance.title)

pre_save.connect(pre_save_static_receiver, sender = Static)


