# -*- coding: utf-8 -*-
"""
© 2018 ALL RIGHTS RESERVED BY Software Assurance LLC

Django settings for ReportIt project.

Generated by 'django-admin startproject' using Django 1.11.8.

"""
from .models import Static
from django.views.generic import DetailView


"""
View class: StaticDetailView class for displayig static pages
Dependency: Serializer fields require with specified format
Request: No
Response: JSON
"""
class StaticDetailView(DetailView):
	model = Static
	template_name = 'base/staticcontent/templates/static_page.html'

	def get_queryset(self):
		language = self.request.META.get('HTTP_LANGUAGE','en')
		if language == 'ar':
			return Static.objects.filter(language__iexact = 'ar',slug = self.kwargs['slug'])
		else:
			return Static.objects.filter(language__iexact = 'en',slug = self.kwargs['slug'])

