# -*- coding: utf-8 -*-
"""
© 2018 ALL RIGHTS RESERVED BY Software Assurance LLC

Django settings for ReportIt project.

Generated by 'django-admin startproject' using Django 1.11.8.

"""
from apns2.client import APNsClient
from apns2.payload import Payload
from django.conf import settings
# from apps.notification.models import AppNotification
class APNSender(object):

    def __init__(self, to, text,badge=0,friends_badge=0, custom={}):

        self._to = to
        self._text = text
        self._badge = badge
        self._data = custom
        self._friends_badge=friends_badge

    def send(self):
        try:

            apn = APNsClient(settings.NOTIFICATIONS_APNS_CERT_PATH, use_sandbox=settings.NOTIFICATIONS_SANDBOX,
                             use_alternative_port=False)
            topic = settings.NOTIFICATIONS_IOS_APP_BUNDLE_ID
            payload = Payload(alert=self._text, sound="default", badge=self._badge, custom=self._data)

            apn.send_notification(self._to, payload, topic)

        except:
            pass
