# -*- coding: utf-8 -*-
"""
© 2018 ALL RIGHTS RESERVED BY Software Assurance LLC

Django settings for ReportIt project.

Generated by 'django-admin startproject' using Django 1.11.8.

"""
from django.conf import settings
from pyfcm import FCMNotification
from datetime import datetime
# from apps.notification.models import AppNotification
class FCMSender(object):

    def __init__(self, to, data):

        self._to = to
        self._data = data

    def send(self):
        try:
            from base.utils.utilities import notification_log
            fcm = FCMNotification(api_key=settings.NOTIFICATIONS_FCM_KEY)
            # print("=============", self._to)
        
            response = fcm.notify_single_device(registration_id=self._to, data_message=self._data)
            print("Android==>",response)
            notification_log(response,"Android")
            return response
        except Exception as e:
            print("error noti:", e)
            return e
            
        # return response
