"""
Django settings for BeerBuddy project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import dj_database_url
from decouple import config, Csv
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'users',
    'base.staticcontent',
    'event',
    'beershop',
    'notification',
    'brewery',
    'ckeditor',
    'ckeditor_uploader',
    'django_crontab',
    'django_mysql',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_FAILURE_VIEW = 'brewery.views.csrf_failure'
ROOT_URLCONF = 'BeerBuddy.urls'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'brewery.backends.EmailBackend',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BeerBuddy.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}

# AUTH_USER_MODEL = "users.User" 

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


AUTH_USER_MODEL = 'users.User'

# CLX MBLOX SMS

CLX_MBLOX_SERVICEPLAN = config('CLX_MBLOX_SERVICEPLAN')
CLX_MBLOX_TOKEN = config('CLX_MBLOX_TOKEN')
CLX_MBLOX_DYNAMIC_SENDER_ID = config('CLX_MBLOX_DYNAMIC_SENDER_ID')

# EMAIL
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'base.exceptions.exception_handler.custom_exception_handler',
    # 'EXCEPTION_HANDLER': 'base.exceptions.exceptions.exception_handler',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'base.api.authentications.JWTCustomAuthentication',
    ),
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S.%fZ",
}

"""
NOTIFICATIONS
"""
NOTIFICATIONS_BASE = os.path.join(BASE_DIR, "base", "communications", "cert")

NOTIFICATIONS_APNS_CERT_NAME = config('NOTIFICATIONS_APNS_CERT_NAME')
NOTIFICATIONS_SANDBOX = config('NOTIFICATIONS_SANDBOX', cast=bool)
NOTIFICATIONS_APNS_CERT_PATH = os.path.join(
    NOTIFICATIONS_BASE, NOTIFICATIONS_APNS_CERT_NAME)
NOTIFICATIONS_IOS_APP_BUNDLE_ID = config('NOTIFICATIONS_IOS_APP_BUNDLE_ID')

NOTIFICATIONS_FCM_KEY = config('NOTIFICATIONS_FCM_KEY')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=config('DEFAULT_ACCESS_TOKEN_LIFETIME', default=7, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('SECRET_KEY'),
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = 'login_success'

SITE_ID = 1

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}


GOOGLE_PLACE_DETAIL_API_KEY = config('GOOGLE_PLACE_DETAIL_API_KEY')
CRONJOBS = [
    ('*/4 * * * *', 'users.tasks.checkin_user',
     '>> /tmp/scheduled_job_check_in.log'),
    ('*/5 * * * *', 'users.tasks.checkout_user',
     '>> /tmp/scheduled_job_check_out.log')
]

import mimetypes
mimetypes.add_type("text/css", ".css", True)

TEMPLATE_DEBUG = DEBUG

# AWS Setting
USE_S3 = config('USE_S3')
if USE_S3 == 'True':
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    # s3 static settings
    # STATIC_LOCATION = 'static'
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    # STATICFILES_STORAGE = 'hello_django.storage_backends.StaticStorage'

    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = f'{config("AWS_STORAGE_FOLDER_NAME")}'

    # PROFILE_MEDIA_LOCATION = f'{config("AWS_STORAGE_FOLDER_NAME")}/profile'
    # PROFILE_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/{PROFILE_MEDIA_LOCATION}/'
    # PROFILE_FILE_STORAGE = 'BeerBuddy.storage_backends.ProfileMediaStorage'

    # OFFERS_MEDIA_LOCATION = f'{config("AWS_STORAGE_FOLDER_NAME")}/offers'
    # OFFERS_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/{OFFERS_MEDIA_LOCATION}/'
    # OFFERS_FILE_STORAGE = 'BeerBuddy.storage_backends.OffersMediaStorage'

    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'


    DEFAULT_FILE_STORAGE = 'BeerBuddy.storage_backends.PublicMediaStorage'

    TEST_MEDIA_LOCATION = 'test'
    TEST_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{TEST_MEDIA_LOCATION}/'
    TEST_FILE_STORAGE = 'BeerBuddy.storage_backends.TestStorage'
else:
    
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_cdn")

# Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "users/web/admin/static"),
    os.path.join(BASE_DIR, "brewery/web/admin/static")
]



